name: Maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: "1 2 * * *"

jobs:
  update-checks:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install -e '.[scraper]'
      - run: cd scripts && ./scrape_checks.py
