name: Release

permissions:
  contents: write

on:
  push:
    branches: [main]
  release:
    types: [published, edited]

jobs:
  create-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@ae59f5ce1c46bfaf372ba9cf49ea97de64939731
        with:
          bump_version_scheme: norelease

  update-major-tag:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@f411bd910a5ad370d4511517e3eac7ff887c90ea

  dist:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pipx run build
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
      - run: pipx run twine check dist/*

  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
